import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Header from './(flim)/components/layouts/Header/Header';
import Footer from './(flim)/components/layouts/Footer';

// const geistSans = localFont({
//     src: '../fonts/GeistVF.woff',
//     variable: '--font-geist-sans',
//     weight: '100 900',
// });
// const geistMono = localFont({
//     src: '../fonts/GeistMonoVF.woff',
//     variable: '--font-geist-mono',
//     weight: '100 900',
// });
const bannerFont = localFont({
    src: '../fonts/BannerFont.woff2',
    variable: '--font-banner',
    weight: '400 500 700',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${bannerFont} antialiased`}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
